### PR TITLE
Operators.( ||> ): typo in example output

### PR DESCRIPTION
**Pull request by sergey-tihon**

### CODE REVIEW

**Comment by dendeli-msft** [comment]
OPS Build status updates of commit _[52abd0a](https://github.com/sergey-tihon/visualfsharpdocs/pull/321/commits/52abd0a8f3d7e118fce0cbaf6a8e068a86085155)_: 

:clock10: **Preparing**: average preparing time is _1 min(s)_

**Comment by dendeli-msft** [comment]
OPS Build status updates of commit _[52abd0a](https://github.com/sergey-tihon/visualfsharpdocs/pull/321/commits/52abd0a8f3d7e118fce0cbaf6a8e068a86085155)_: 

:clock10: **Full build**: average full build time is _2 min(s) 3 sec(s)_ [calculated from last _1_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by dendeli-msft** [comment]
OPS Build status updates of commit _[52abd0a](https://github.com/sergey-tihon/visualfsharpdocs/pull/321/commits/52abd0a8f3d7e118fce0cbaf6a8e068a86085155)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/conceptual/seq.tail[&#39;t]-function-[fsharp].md](https://github.com/sergey-tihon/visualfsharpdocs/blob/patch-1/docs/conceptual/seq.tail[&#39;t]-function-[fsharp].md) | :warning:Warning | | [Details](#user-content-docs%2Fconceptual%2Fseq.tail%5B%26%2339%3Bt%5D-function-%5Bfsharp%5D.md)
[docs/conceptual/operators.[-hh]-]['t1,'t2,'u]-function-[fsharp].md](https://github.com/sergey-tihon/visualfsharpdocs/blob/patch-1/docs/conceptual/operators.[-hh]-]['t1,'t2,'u]-function-[fsharp].md) | :white_check_mark:Succeeded | |

<a name="docs%2Fconceptual%2Fseq.tail%5B%26%2339%3Bt%5D-function-%5Bfsharp%5D.md"></a>
### [docs/conceptual/seq.tail[&#39;t]-function-[fsharp].md](https://github.com/sergey-tihon/visualfsharpdocs/blob/patch-1/docs/conceptual/seq.tail[&#39;t]-function-[fsharp].md)
 - **Line 48**: **[Warning]** Invalid file link:(~/seq.head[&amp;#39;t%5D-function-%5Bfsharp%5D.md).
 - **Line 77**: **[Warning]** Invalid file link:(~/seq.head[&amp;#39;t%5D-function-%5Bfsharp%5D.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C2%5Cd6a0e3a6-9e9b-b4c0-7059-c20dbf9462d1%5CPullRequest%5C201901020757559988-321%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qZIFbaBlKKd8qJnNR2soD2cols%2BQJjt5XxIjrmB0N%2BY%3D&st=2019-01-02T07%3A55%3A51Z&se=2019-02-02T08%3A00%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sergey-tihon** [comment]
@cartermp can you please suggest what should be done to merge this PR?

https://msdn.microsoft.com/visualfsharpdocs/conceptual/operators.%5b-hh%5d-%5d%5b%27t1%2c%27t2%2c%27u%5d-function-%5bfsharp%5d

image

**Pull request closed without merging**
